apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: exdns-test
  labels:
    f5cr: "true"
spec:
  domainName: "test.example.com"
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  - dnsRecordType: A
    loadBalanceMethod: round-robin
    dataServerName: /Common/TP_F5
    monitor:
      type: https
      send: "GET /"
      recv: ""
      interval: 10
      timeout: 10
