# policyName can be used to attach profiles/policies defined in Policy CRD
apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: reencrypt-tls-1
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  tls:
    termination: reencrypt
    clientSSL: /Common/clientssl
    serverSSL: /Common/serverssl
    reference: bigip
  hosts:
  - test.example.com

---
apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: hello-with-policy-1
  namespace: nginx-ingress
spec:
  host: test.example.com
  virtualServerAddress: 10.8.38.112
  tlsProfileName: reencrypt-tls-1
  policyName: hello-policy-1
  httpTraffic: none
  pools:
    - monitor:
        interval: 13
        recv: 
        send: /
        timeout: 10
        type: https
      path: /
      service: "nginx-ingress"
      servicePort: 443
  snat: auto

---
apiVersion: cis.f5.com/v1
kind: Policy
metadata:
  labels:
    f5cr: "true"
  name: hello-policy-1
  namespace: nginx-ingress
spec:
  profiles:
    http: /Common/http

